name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build
      run: echo "Add your build commands here"

    - name: Test
      run: echo "Add your test commands here"

  build-maven:
    runs-on: windows-latest

    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
